[build]
  command = "flutter build web"
  publish = "build/web"
  functions = "functions"  # Optional: If you have serverless functions

[context.production.environment]
  FLUTTER_VERSION = "3.16.9"  
[context.deploy-preview.environment]
  FLUTTER_VERSION = "3.16.9" 
[context.branch-deploy.environment]
  FLUTTER_VERSION = "3.16.9" 