[build]
  command = "flutter build web --web-renderer canvaskit "
  publish = "build/web"
  functions = "functions"  # Optional: If you have serverless functions
  environment = { FLUTTER_VERSION = "3.16.9"}

[context.production.environment]
  FLUTTER_VERSION = "3.16.9"  
[context.deploy-preview.environment]
  FLUTTER_VERSION = "3.16.9" 
[context.branch-deploy.environment]
  FLUTTER_VERSION = "3.16.9" 